#!/usr/bin/expect

set MYSQL_ROOT_PASSWORD="root1234"

spawn mysql_secure_installation

expect "Enter password for user root:"
send "$MYSQL_ROOT_PASSWORD\r"

expect "New password:"
send "$MYSQL_ROOT_PASSWORD\r"

expect "Re-enter new password:"
send "$MYSQL_ROOT_PASSWORD\r"

expect "Remove anonymous users?"
send "n\r"

expect "Disallow root login remotely?"
send "n\r"

expect "Remove test database and access to it?"
send "n\r"

expect "Reload privilege tables now?"
send "n\r"

expect eof
