#!/usr/bin/expect

set timeout -1

# Set the password for the MySQL root user
set mysql_password "root1234"

# Run mysql_secure_installation without prompts
spawn mysql_secure_installation

expect "Enter password for user root:"
send "$mysql_password\r"

expect "Change the password for root ? ((Press y|Y for Yes, any other key for No) :"
send "n\r"

expect "Remove anonymous users? (Press y|Y for Yes, any other key for No) :"
send "y\r"

expect "Disallow root login remotely? (Press y|Y for Yes, any other key for No) :"
send "y\r"

expect "Remove test database and access to it? (Press y|Y for Yes, any other key for No) :"
send "y\r"

expect "Reload privilege tables now? (Press y|Y for Yes, any other key for No) :"
send "y\r"

expect eof
